In [ ]:
!pip install tabula-py
import tabula
import numpy as np
import pandas as pd

Collecting tabula-py
  Downloading tabula_py-2.10.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.12/dist-packages (from tabula-py) (2.2.2)
Requirement already satisfied: numpy>1.24.4 in /usr/local/lib/python3.12/dist-packages (from tabula-py) (2.0.2)
Requirement already satisfied: distro in /usr/local/lib/python3.12/dist-packages (from tabula-py) (1.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.25.3->tabula-py) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.17.0)
Downloading tabula_py-2.10.0-py3-none-any.whl (12.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 49.0 MB/s eta 0:00:00
Installing collected packages: tabula-py
Successfully installed tabula-py-2.10.0

# Fatalities Data

In [ ]:
pdf_file = "crashes.pdf"
csv_file = "crashes.csv"

In [ ]:
tabula.convert_into(
    input_path=pdf_file,
    output_path=csv_file,
    output_format="csv",
    pages="all"
)

WARNING:tabula.backend:Failed to import jpype dependencies. Fallback to subprocess.
WARNING:tabula.backend:No module named 'jpype'

In [ ]:
crashes_csv = pd.read_csv('crashes.csv')

In [ ]:
crashes = crashes_csv

In [ ]:
crashes = crashes.rename(columns={"Unnamed: 0": "City", "Unnamed: 1": "2023 Total Killed", "Unnamed: 2": "2023 Pedestrians Killed", "Unnamed: 3": "Percent of Total Killed", "Unnamed: 4": "2023 Population"})
crashes.drop(columns=["Fatality Rate per"], inplace=True)

In [ ]:
crashes

,City,2023 Total Killed,2023 Pedestrians Killed,Percent of Total Killed,2023 Population
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Fatalities,NaN,NaN
2,City,NaN,NaN,NaN,NaN
3,NaN,NaN,2023,Percent,NaN
4,NaN,2023 Total,Pedestrians,of Total,2023
...,...,...,...,...,...
236,"Kansas City, KS",26,7,26.9,"152,933"
237,"Sunnyvale, CA",7,4,57.1,"151,967"
238,"Bellevue, WA",1,0,0.0,"151,574"
239,"Joliet, IL",11,1,9.1,"150,489"
240,"Naperville, IL",3,1,33.3,"150,245"

In [ ]:
crashes.drop(index=[0,1,2,3,4,5,27,28,29,30,31,32,33,55,56,57,58,59,60,61,83,84,85,86,87,88,89,111,112,113,114,115,116,117,139,140,141,142,143,144,145,167,168,169,170,171,172,173,195,196,197,198,199,200,201,223,224,225,226,227,228,229], inplace=True)
crashes.reset_index(drop=True, inplace=True)

In [ ]:
crashes

,City,2023 Total Killed,2023 Pedestrians Killed,Percent of Total Killed,2023 Population
0,"New York, NY",204,85,41.7,"8,258,035"
1,"Los Angeles, CA",329,145,44.1,"3,820,914"
2,"Chicago, IL",167,51,30.5,"2,664,452"
3,"Houston, TX",296,98,33.1,"2,314,157"
4,"Phoenix, AZ",308,109,35.4,"1,650,070"
...,...,...,...,...,...
174,"Kansas City, KS",26,7,26.9,"152,933"
175,"Sunnyvale, CA",7,4,57.1,"151,967"
176,"Bellevue, WA",1,0,0.0,"151,574"
177,"Joliet, IL",11,1,9.1,"150,489"
178,"Naperville, IL",3,1,33.3,"150,245"

In [ ]:
crashes['Total Fatality Rate Per 100,000 Population'] = [2.47, 8.61, 6.27, 12.79, 18.67, 8.71, 11.90, 6.77, 15.89, 16.64, 9.59, 12.06, 6.29, 10.73, 9.77, 13.65, 4.20, 4.64, 10.61, 14.37, 15.99, 6.48, 12.37, 6.35, 2.75, 20.69, 10.94, 18.94, 39.44, 8.14, 14.07, 19.45, 26.86, 9.53, 13.11, 13.49, 16.44, 19.19, 9.82, 6.83, 8.92, 14.70, 8.16, 8.90, 7.10, 6.59, 13.30, 18.94, 12.64, 10.54, 10.10, 16.45, 16.48, 16.27, 5.56, 7.64, 1.19, 12.16, 15.31, 10.95, 10.98, 11.69, 3.81, 12.21, 7.73, 10.17, 4.28, 6.60, 10.92, 8.78, 4.07, 4.11, 5.86, 5.24, 8.43, 18.46, 6.06, 11.06, 4.72, 6.55, 8.01, 4.37, 5.56, 14.61, 13.19, 9.87, 8.93, 8.65, 6.70,18.12, 14.23, 5.71, 10.23, 9.04, 6.37, 6.50, 8.72, 12.65, 4.86, 12.86, 2.22, 9.36, 3.57, 23.69, 20.19, 9.94, 19.13, 9.59, 13.46, 4.22, 5.65, 8.56, 11.44, 10.97, 2.89, 3.37, 8.68, 5.81, 26.00, 11.86, 10.38, 9.89, 12.88, 22.40, 8.55, 7.05, 30.78, 4.06, 24.92, 9.66, 8.65, 14.34, 5.73, 5.24, 9.47, 18.44, 11.66, 3.21, 19.78, 17.91, 6.55, 20.26, 10.96, 17.15, 2.78, 2.80, 15.17, 6.75, 5.07, 7.89, 0.57, 9.17, 6.43, 7.63, 19.39, 8.23, 5.94, 15.04, 9.07, 12.39, 13.11, 8.77, 1.25, 5.66, 9.47, 10.74, 23.64, 5.11 , 12.82, 5.14, 14.80, 1.29, 7.80, 9.76, 17.00, 4.61, 0.66, 7.31, 2.00 ]
crashes['Pedestrian Fatality Rate per 100,000 Population'] = [1.03, 3.79, 1.91, 4.23, 6.61, 3.61, 4.68, 2.81, 5.07, 4.16, 3.98, 4.19, 2.78, 2.63, 2.52, 3.53, 2.23, 1.72, 3.91, 3.70, 4.51, 2.06, 2.95, 1.97, 1.07, 5.69, 3.65, 4.49, 9.21, 4.07, 3.21, 9.28, 6.40, 3.66, 4.94, 2.74, 4.50, 2.94, 1.64, 0.62, 1.87, 6.80, 1.98, 3.56, 2.98, 1.65, 4.60, 4.13, 4.71, 2.26, 2.52, 4.30, 4.39, 3.31, 2.05, 1.76, 0.59, 4.68, 6.87, 3.44, 4.08, 2.84, 0.64, 3.21, 4.83, 3.28, 0.66, 2.31, 3.64, 2.36, 0.34, 1.03, 2.41, 2.10, 1.40, 3.19, 2.14, 1.78, 0.73, 3.64, 2.91, 0.73, 1.85, 3.37, 2.64, 3.04, 2.33, 1.57, 0.79, 6.30, 2.37, 1.22, 1.64, 2.05, 2.97, 0.87, 4.79, 3.49, 1.77, 1.77, 0.89, 1.34, 0.89, 8.05, 3.14, 3.62, 7.29, 5.02, 4.64, 1.41, 1.88, 0.95, 2.38, 3.34, 0.48, 0.00, 5.79, 1.45, 10.30, 4.94, 4.45, 1.48, 2.48, 8.46, 2.01, 0.50, 4.54, 0.51, 6.61, 3.05, 1.02, 3.07, 1.04, 2.10, 5.78, 3.16, 3.18, 0.53, 7.49, 7.06, 1.64, 8.21, 2.74, 2.77, 1.67, 0.56, 2.25, 2.81, 0.56, 2.25, 0.57, 2.29, 1.75, 1.17, 2.94, 1.18, 2.38, 2.41, 0.60, 1.86, 4.37, 2.51, 0.63, 0.00, 1.26, 0.63, 8.31, 0.00, 3.21, 0.64, 4.51, 0.00, 2.60, 4.56, 4.58, 2.63, 0.00, 0.66, 0.67]
crashes

,City,2023 Total Killed,2023 Pedestrians Killed,Percent of Total Killed,2023 Population,"Total Fatality Rate Per 100,000 Population","Pedestrian Fatality Rate per 100,000 Population"
0,"New York, NY",204,85,41.7,"8,258,035",2.47,1.03
1,"Los Angeles, CA",329,145,44.1,"3,820,914",8.61,3.79
2,"Chicago, IL",167,51,30.5,"2,664,452",6.27,1.91
3,"Houston, TX",296,98,33.1,"2,314,157",12.79,4.23
4,"Phoenix, AZ",308,109,35.4,"1,650,070",18.67,6.61
...,...,...,...,...,...,...,...
174,"Kansas City, KS",26,7,26.9,"152,933",17.00,4.58
175,"Sunnyvale, CA",7,4,57.1,"151,967",4.61,2.63
176,"Bellevue, WA",1,0,0.0,"151,574",0.66,0.00
177,"Joliet, IL",11,1,9.1,"150,489",7.31,0.66
178,"Naperville, IL",3,1,33.3,"150,245",2.00,0.67

# Daylight Condition

In [ ]:
pdf_file = "FileName.txt"
csv_file = "lighting.csv"

In [ ]:
tabula.convert_into(
    input_path=pdf_file,
    output_path=csv_file,
    output_format="csv",
    pages="all"
)

ERROR:tabula.backend:Error from tabula-java:
Error: Error: End-of-File, expected line

CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', '/usr/local/lib/python3.12/dist-packages/tabula/tabula-1.0.5-jar-with-dependencies.jar', '--pages', 'all', '--guess', '--format', 'CSV', '--outfile', 'lighting.csv', 'FileName.txt']' returned non-zero exit status 1.